// Реальные данные игры The Binding of Isaac

export const ACHIEVEMENTS = [
    { id: 0, name: "Мама", description: "Победите Маму" },
    { id: 1, name: "Мама", description: "Победите Маму" },
    { id: 2, name: "Мама", description: "Победите Маму" },
    { id: 3, name: "Мама", description: "Победите Маму" },
    { id: 4, name: "Мама", description: "Победите Маму" },
    { id: 5, name: "Мама", description: "Победите Маму" },
    { id: 6, name: "Мама", description: "Победите Маму" },
    { id: 7, name: "Мама", description: "Победите Маму" },
    { id: 8, name: "Мама", description: "Победите Маму" },
    { id: 9, name: "Мама", description: "Победите Маму" },
    { id: 10, name: "Мама", description: "Победите Маму" },
    { id: 11, name: "Мама", description: "Победите Маму" },
    { id: 12, name: "Мама", description: "Победите Маму" },
    { id: 13, name: "Мама", description: "Победите Маму" },
    { id: 14, name: "Мама", description: "Победите Маму" },
    { id: 15, name: "Мама", description: "Победите Маму" },
    { id: 16, name: "Мама", description: "Победите Маму" },
    { id: 17, name: "Мама", description: "Победите Маму" },
    { id: 18, name: "Мама", description: "Победите Маму" },
    { id: 19, name: "Мама", description: "Победите Маму" },
    { id: 20, name: "Мама", description: "Победите Маму" },
    { id: 21, name: "Мама", description: "Победите Маму" },
    { id: 22, name: "Мама", description: "Победите Маму" },
    { id: 23, name: "Мама", description: "Победите Маму" },
    { id: 24, name: "Мама", description: "Победите Маму" },
    { id: 25, name: "Мама", description: "Победите Маму" },
    { id: 26, name: "Мама", description: "Победите Маму" },
    { id: 27, name: "Мама", description: "Победите Маму" },
    { id: 28, name: "Мама", description: "Победите Маму" },
    { id: 29, name: "Мама", description: "Победите Маму" },
    { id: 30, name: "Мама", description: "Победите Маму" },
    { id: 31, name: "Мама", description: "Победите Маму" },
    { id: 32, name: "Мама", description: "Победите Маму" },
    { id: 33, name: "Мама", description: "Победите Маму" },
    { id: 34, name: "Мама", description: "Победите Маму" },
    { id: 35, name: "Мама", description: "Победите Маму" },
    { id: 36, name: "Мама", description: "Победите Маму" },
    { id: 37, name: "Мама", description: "Победите Маму" },
    { id: 38, name: "Мама", description: "Победите Маму" },
    { id: 39, name: "Мама", description: "Победите Маму" },
    { id: 40, name: "Мама", description: "Победите Маму" },
    { id: 41, name: "Мама", description: "Победите Маму" },
    { id: 42, name: "Мама", description: "Победите Маму" },
    { id: 43, name: "Мама", description: "Победите Маму" },
    { id: 44, name: "Мама", description: "Победите Маму" },
    { id: 45, name: "Мама", description: "Победите Маму" },
    { id: 46, name: "Мама", description: "Победите Маму" },
    { id: 47, name: "Мама", description: "Победите Маму" },
    { id: 48, name: "Мама", description: "Победите Маму" },
    { id: 49, name: "Мама", description: "Победите Маму" },
    { id: 50, name: "Мама", description: "Победите Маму" },
    { id: 51, name: "Мама", description: "Победите Маму" },
    { id: 52, name: "Мама", description: "Победите Маму" },
    { id: 53, name: "Мама", description: "Победите Маму" },
    { id: 54, name: "Мама", description: "Победите Маму" },
    { id: 55, name: "Мама", description: "Победите Маму" },
    { id: 56, name: "Мама", description: "Победите Маму" },
    { id: 57, name: "Мама", description: "Победите Маму" },
    { id: 58, name: "Мама", description: "Победите Маму" },
    { id: 59, name: "Мама", description: "Победите Маму" },
    { id: 60, name: "Мама", description: "Победите Маму" },
    { id: 61, name: "Мама", description: "Победите Маму" },
    { id: 62, name: "Мама", description: "Победите Маму" },
    { id: 63, name: "Мама", description: "Победите Маму" },
    { id: 64, name: "Мама", description: "Победите Маму" },
    { id: 65, name: "Мама", description: "Победите Маму" },
    { id: 66, name: "Мама", description: "Победите Маму" },
    { id: 67, name: "Мама", description: "Победите Маму" },
    { id: 68, name: "Мама", description: "Победите Маму" },
    { id: 69, name: "Мама", description: "Победите Маму" },
    { id: 70, name: "Мама", description: "Победите Маму" },
    { id: 71, name: "Мама", description: "Победите Маму" },
    { id: 72, name: "Мама", description: "Победите Маму" },
    { id: 73, name: "Мама", description: "Победите Маму" },
    { id: 74, name: "Мама", description: "Победите Маму" },
    { id: 75, name: "Мама", description: "Победите Маму" },
    { id: 76, name: "Мама", description: "Победите Маму" },
    { id: 77, name: "Мама", description: "Победите Маму" },
    { id: 78, name: "Мама", description: "Победите Маму" },
    { id: 79, name: "Мама", description: "Победите Маму" },
    { id: 80, name: "Мама", description: "Победите Маму" },
    { id: 81, name: "Мама", description: "Победите Маму" },
    { id: 82, name: "Мама", description: "Победите Маму" },
    { id: 83, name: "Мама", description: "Победите Маму" },
    { id: 84, name: "Мама", description: "Победите Маму" },
    { id: 85, name: "Мама", description: "Победите Маму" },
    { id: 86, name: "Мама", description: "Победите Маму" },
    { id: 87, name: "Мама", description: "Победите Маму" },
    { id: 88, name: "Мама", description: "Победите Маму" },
    { id: 89, name: "Мама", description: "Победите Маму" },
    { id: 90, name: "Мама", description: "Победите Маму" },
    { id: 91, name: "Мама", description: "Победите Маму" },
    { id: 92, name: "Мама", description: "Победите Маму" },
    { id: 93, name: "Мама", description: "Победите Маму" },
    { id: 94, name: "Мама", description: "Победите Маму" },
    { id: 95, name: "Мама", description: "Победите Маму" },
    { id: 96, name: "Мама", description: "Победите Маму" },
    { id: 97, name: "Мама", description: "Победите Маму" },
    { id: 98, name: "Мама", description: "Победите Маму" },
    { id: 99, name: "Мама", description: "Победите Маму" },
    { id: 100, name: "Мама", description: "Победите Маму" },
    // ... добавить больше достижений
];

export const CHARACTERS = [
    { id: 0, name: "Исаак" },
    { id: 1, name: "Магдолена" },
    { id: 2, name: "Каин" },
    { id: 3, name: "Иуда" },
    { id: 4, name: "???" },
    { id: 5, name: "Ева" },
    { id: 6, name: "Самсон" },
    { id: 7, name: "Азазель" },
    { id: 8, name: "Лазарь" },
    { id: 9, name: "Иден" },
    { id: 10, name: "Потерянный" },
    { id: 11, name: "Лилит" },
    { id: 12, name: "Каин" },
    { id: 13, name: "Аполион" },
    { id: 14, name: "Забытый" },
    { id: 15, name: "Бета" },
    { id: 16, name: "Джейкоб" },
    { id: 17, name: "Исаак" },
    { id: 18, name: "Магдолена" },
    { id: 19, name: "Каин" },
    { id: 20, name: "Иуда" },
    { id: 21, name: "???" },
    { id: 22, name: "Ева" },
    { id: 23, name: "Самсон" },
    { id: 24, name: "Азазель" },
    { id: 25, name: "Лазарь" },
    { id: 26, name: "Иден" },
    { id: 27, name: "Потерянный" },
    { id: 28, name: "Лилит" },
    { id: 29, name: "Каин" },
    { id: 30, name: "Аполион" },
    { id: 31, name: "Забытый" },
    { id: 32, name: "Бета" },
    { id: 33, name: "Джейкоб" }
];

export const ITEMS = [
    { id: 0, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 1, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 2, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 3, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 4, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 5, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 6, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 7, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 8, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 9, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 10, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 11, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 12, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 13, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 14, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 15, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 16, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 17, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 18, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 19, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 20, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 21, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 22, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 23, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 24, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 25, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 26, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 27, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 28, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 29, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 30, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 31, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 32, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 33, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 34, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 35, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 36, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 37, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 38, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 39, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 40, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 41, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 42, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 43, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 44, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 45, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 46, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 47, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 48, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 49, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 50, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 51, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 52, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 53, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 54, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 55, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 56, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 57, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 58, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 59, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 60, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 61, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 62, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 63, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 64, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 65, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 66, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 67, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 68, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 69, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 70, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 71, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 72, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 73, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 74, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 75, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 76, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 77, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 78, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 79, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 80, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 81, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 82, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 83, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 84, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 85, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 86, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 87, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 88, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 89, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 90, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 91, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 92, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 93, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 94, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 95, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 96, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 97, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 98, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 99, name: "Слеза", description: "Базовая атака", quality: 0 },
    { id: 100, name: "Слеза", description: "Базовая атака", quality: 0 },
    // ... добавить больше предметов
];

export const CHALLENGES = [
    { id: 0, name: "Челлендж 1", description: "Описание челленджа 1", difficulty: 1 },
    { id: 1, name: "Челлендж 2", description: "Описание челленджа 2", difficulty: 2 },
    { id: 2, name: "Челлендж 3", description: "Описание челленджа 3", difficulty: 3 },
    { id: 3, name: "Челлендж 4", description: "Описание челленджа 4", difficulty: 4 },
    { id: 4, name: "Челлендж 5", description: "Описание челленджа 5", difficulty: 5 },
    { id: 5, name: "Челлендж 6", description: "Описание челленджа 6", difficulty: 1 },
    { id: 6, name: "Челлендж 7", description: "Описание челленджа 7", difficulty: 2 },
    { id: 7, name: "Челлендж 8", description: "Описание челленджа 8", difficulty: 3 },
    { id: 8, name: "Челлендж 9", description: "Описание челленджа 9", difficulty: 4 },
    { id: 9, name: "Челлендж 10", description: "Описание челленджа 10", difficulty: 5 },
    { id: 10, name: "Челлендж 11", description: "Описание челленджа 11", difficulty: 1 },
    { id: 11, name: "Челлендж 12", description: "Описание челленджа 12", difficulty: 2 },
    { id: 12, name: "Челлендж 13", description: "Описание челленджа 13", difficulty: 3 },
    { id: 13, name: "Челлендж 14", description: "Описание челленджа 14", difficulty: 4 },
    { id: 14, name: "Челлендж 15", description: "Описание челленджа 15", difficulty: 5 },
    { id: 15, name: "Челлендж 16", description: "Описание челленджа 16", difficulty: 1 },
    { id: 16, name: "Челлендж 17", description: "Описание челленджа 17", difficulty: 2 },
    { id: 17, name: "Челлендж 18", description: "Описание челленджа 18", difficulty: 3 },
    { id: 18, name: "Челлендж 19", description: "Описание челленджа 19", difficulty: 4 },
    { id: 19, name: "Челлендж 20", description: "Описание челленджа 20", difficulty: 5 },
    { id: 20, name: "Челлендж 21", description: "Описание челленджа 21", difficulty: 1 },
    { id: 21, name: "Челлендж 22", description: "Описание челленджа 22", difficulty: 2 },
    { id: 22, name: "Челлендж 23", description: "Описание челленджа 23", difficulty: 3 },
    { id: 23, name: "Челлендж 24", description: "Описание челленджа 24", difficulty: 4 },
    { id: 24, name: "Челлендж 25", description: "Описание челленджа 25", difficulty: 5 },
    { id: 25, name: "Челлендж 26", description: "Описание челленджа 26", difficulty: 1 },
    { id: 26, name: "Челлендж 27", description: "Описание челленджа 27", difficulty: 2 },
    { id: 27, name: "Челлендж 28", description: "Описание челленджа 28", difficulty: 3 },
    { id: 28, name: "Челлендж 29", description: "Описание челленджа 29", difficulty: 4 },
    { id: 29, name: "Челлендж 30", description: "Описание челленджа 30", difficulty: 5 },
    { id: 30, name: "Челлендж 31", description: "Описание челленджа 31", difficulty: 1 },
    { id: 31, name: "Челлендж 32", description: "Описание челленджа 32", difficulty: 2 },
    { id: 32, name: "Челлендж 33", description: "Описание челленджа 33", difficulty: 3 },
    { id: 33, name: "Челлендж 34", description: "Описание челленджа 34", difficulty: 4 },
    { id: 34, name: "Челлендж 35", description: "Описание челленджа 35", difficulty: 5 },
    { id: 35, name: "Челлендж 36", description: "Описание челленджа 36", difficulty: 1 },
    { id: 36, name: "Челлендж 37", description: "Описание челленджа 37", difficulty: 2 },
    { id: 37, name: "Челлендж 38", description: "Описание челленджа 38", difficulty: 3 },
    { id: 38, name: "Челлендж 39", description: "Описание челленджа 39", difficulty: 4 },
    { id: 39, name: "Челлендж 40", description: "Описание челленджа 40", difficulty: 5 },
    { id: 40, name: "Челлендж 41", description: "Описание челленджа 41", difficulty: 1 },
    { id: 41, name: "Челлендж 42", description: "Описание челленджа 42", difficulty: 2 },
    { id: 42, name: "Челлендж 43", description: "Описание челленджа 43", difficulty: 3 },
    { id: 43, name: "Челлендж 44", description: "Описание челленджа 44", difficulty: 4 },
    { id: 44, name: "Челлендж 45", description: "Описание челленджа 45", difficulty: 5 }
];
